// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrZtDS9lBiOA-KZIB61CC43KL2yEKlkk',
    appId: '1:465078550816:web:54428ca9c48db03b99d745',
    messagingSenderId: '465078550816',
    projectId: 'green-waste-1d4dc',
    authDomain: 'green-waste-1d4dc.firebaseapp.com',
    databaseURL: 'https://green-waste-1d4dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-waste-1d4dc.appspot.com',
    measurementId: 'G-YWHBNXLJVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZVMZLTYB_lnW3WYmG0feuc4OLMweS_Q',
    appId: '1:465078550816:android:1fa765a20e948a7c99d745',
    messagingSenderId: '465078550816',
    projectId: 'green-waste-1d4dc',
    databaseURL: 'https://green-waste-1d4dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-waste-1d4dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjViOJJjL0HcsyYg57SCNrGSx5Myu6wk',
    appId: '1:465078550816:ios:295a5663bf29511699d745',
    messagingSenderId: '465078550816',
    projectId: 'green-waste-1d4dc',
    databaseURL: 'https://green-waste-1d4dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-waste-1d4dc.appspot.com',
    iosClientId: '465078550816-ekvctq82j7lt8re6fvug6h2ac7g0i07f.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGreenWaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjViOJJjL0HcsyYg57SCNrGSx5Myu6wk',
    appId: '1:465078550816:ios:295a5663bf29511699d745',
    messagingSenderId: '465078550816',
    projectId: 'green-waste-1d4dc',
    databaseURL: 'https://green-waste-1d4dc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-waste-1d4dc.appspot.com',
    iosClientId: '465078550816-ekvctq82j7lt8re6fvug6h2ac7g0i07f.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGreenWaste',
  );
}
